digest: 689aa290
name: dataset
profile: '{"num_rows": 38, "num_elements": 152}'
schema: '{"mlflow_colspec": [{"type": "double", "name": "sepal length", "required":
  true}, {"type": "double", "name": "sepal width", "required": true}, {"type": "double",
  "name": "petal length", "required": true}, {"type": "double", "name": "petal width",
  "required": true}]}'
source: '{"tags": {"mlflow.user": "mateus", "mlflow.source.name": "src/scripts/train.py",
  "mlflow.source.type": "LOCAL", "mlflow.source.git.commit": "ab347c9de428ed5b36529db199d9f79c34fc514a"}}'
source_type: code
